In [17]:
import pandas as pd
df= pd.read_csv("raw_data.csv")
print(df)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
info={
    "Name" : ["chinnu","chiddhu","chinnulu","chinddhulu"],
      "cgpa" : [8.9,9.90,8.9,9.8]
}
pd.DataFrame(info)

#Series 
s=pd.Series([1,2,3,4],index=['A','B','C','D'])
print(s,type(s))
#indexing
s[:3]
#labelling
s['A':'B']

A    1
B    2
C    3
D    4
dtype: int64 <class 'pandas.core.series.Series'>

A    1
B    2
dtype: int64

In [5]:
pd.DataFrame(info)
df.describe()

df.info()
df.nunique()
print(df.index)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes
RangeIndex(start=0, stop=11, step=1)

In [6]:
cp=pd.DataFrame(info)
cp
print(cp.index)
print(cp.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'cgpa'], dtype='object')

In [7]:
aq= pd.read_csv("globalAirQuality.csv")
aq.tail(5)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [8]:
aq.info()
aq.head(5)
#shape ,size,dtype ,col's,index.... are properties notfunction/meyhod not called
print(aq.shape)
aq.nunique()
print(aq.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB
(18000, 15)
Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [14]:
#Selecting
#col'S
aq["co"]
#row and col's
aq.loc[9,["aqi","city"]]
# include end values
aq.loc[5:9,["co","no2"]]
aq.iloc[8:11]#exclude end
aq.at[7,"city"]#single ele by label
aq.iat[0,2]#single with indexing

#Feltering

aq[aq["aqi"]<30]

aq[aq["aqi"]<30][["city"]]


#Query
aq.query("city == 'Zurich' & aqi<50")[["city","aqi","timestamp"]]


#aq["co","aqi"]

         city  aqi                   timestamp
17713  Zurich   48  2025-11-07 19:25:17.554219
17811  Zurich   45  2025-11-11 21:25:17.554219
17962  Zurich   47  2025-11-18 04:25:17.554219
17986  Zurich   38  2025-11-19 04:25:17.554219

In [22]:
ars= pd.Series([1,2,3,4,5,6])
ars[0]=10
ars
change_ars=ars.drop(1)
change_ars

0    10
2     3
3     4
4     5
5     6
dtype: int64